### ISSUE TITLE
Review request for Group project Setup

### ISSUE THREAD

**Issue by mercymugambi** [lilskyex0x/JS-CapstoneProject-M2#21]
## On this milestone
We managed to do the setup for the project guided by the instructions provided.
Below is the link to the project created on Kanban
(https://github.com/lilskyex0x/JS-CapstoneProject-M2/projects/1)

Tasks are assigned to two members namely:
@mercymugambi 
@lilskyex0x

**Comment by amejid** [comment]
Hi team, 

Your project is complete!
Congratulations! 🎉 

<img src="https://media0.giphy.com/media/RltjLEzzB87ErJdxHz/giphy.gif"/>

## Highlights
- Project follows the template :heavy_check_mark: 
- All cards assigned to members :heavy_check_mark: 
- Fair task distribution :heavy_check_mark: 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
